feat: avatar 1st commit
ankit9015/socket-ui pull request #2
Opened 2022-02-06 03:33 UTC by ankit9015

Feat consists:
1. Circle avatar (default)
2. Size variation for avatar -sm -md -l
3. Square avatar
4. Avatar for icons and texts

Will update later: To create this example I used avatar.css directly for avatar.html. I will later connect this to component css when I start working on documentation and do the necessary edits.
![Uploading avatar.png…]()

2022-02-06 04:32 UTC, paarthbajaj reviewed
Everything looks good. No suggestions from my side. Ready to merge.

2022-02-07 13:48 UTC, SAYUK09 requested changes
Clean code. Here are a few suggestions you can think about.

2022-02-07 13:48 UTC, SAYUK09 commented on avatar.css
> +    height: 3ex;
can we use `em` instead of `ex` if possible? We can explore a bit.

2022-02-07 13:48 UTC, SAYUK09 commented on avatar.css
> +.avatar-l {
We can use `lg` instead of `l` as it is more standard

2022-02-07 13:48 UTC, SAYUK09 commented on avatar.html
> +    <img class="avatar avatar-l " src="https://picsum.photos/id/1/200/300" alt="">
Don't leave the `alt` tag empty for accessibility purposes.

2022-02-07 13:48 UTC, SAYUK09 commented on avatar.html
> +    <title>SocketUI | Components | Avatar</title>
We can reverse the order. Start with **Avatar** followed by **Components**

2022-02-08 08:03 UTC, paarthbajaj approved these changes

2022-02-09 20:23 UTC, merged