Feat card
ankit9015/socket-ui pull request #8
Opened 2022-02-12 19:40 UTC by ankit9015

Feature card includes:
1. Cards with badges
2. Cards with dismiss
3. Cards with text overlay
4. Text only cards
5. Vertical/Horizontal cards
6. Cards with shadow

![cards](https://user-images.githubusercontent.com/67504902/153725884-cbb518e4-c2f0-4cd0-9005-9009375b6a5f.png)

2022-02-12 19:49 UTC, sushil-mod commented on components/cards/card.css
> +    font-size: 20px;
use rem if possible

2022-02-12 19:49 UTC, sushil-mod commented on components/cards/card.css
> +
if possible use color variable

2022-02-12 19:50 UTC, sushil-mod approved these changes
go through comment , then you can merge !

2022-02-17 14:21 UTC, ankit9015 commented on components/cards/card.css
> +    font-size: 20px;
Changes done

2022-02-17 14:21 UTC, ankit9015 commented on components/cards/card.css
> +
Changes done

2022-02-17 14:26 UTC, Kothalkarpriya requested changes
Look into my comments

2022-02-17 14:26 UTC, Kothalkarpriya commented on components/cards/card.css
> +.card-img {
remove empty selectors

2022-02-17 14:26 UTC, Kothalkarpriya commented on components/cards/card.css
> +
remove extra spaces

2022-02-17 14:26 UTC, Kothalkarpriya commented on components/cards/cards.html
> +            <img class="card-img" src=https://picsum.photos/200/200 alt="">
for image tag do use / before closing it, as it is self closing tag

2022-02-18 11:18 UTC, merged